### ISSUE TITLE
How does shared-dependencies generated on the site(https://react.microfrontends.app/importmap.json)?

### ISSUE THREAD

**Issue by jiushiwoyuze** [react-microfrontends/shared-dependencies#3]
Hi, I am confused about why https://react.microfrontends.app/importmap.json has "@react-mf/*" dependencies which does not appear in the code?

In https://react.microfrontends.app/importmap.json
![image](https://user-images.githubusercontent.com/5416077/112125417-60fbc980-8bfe-11eb-8e3d-0c852ff13f55.png)

In code
![image](https://user-images.githubusercontent.com/5416077/112125528-7cff6b00-8bfe-11eb-9908-41d30fdc9c05.png)

Are the "@react-mf/*" dependencies added manually?

**Comment by joeldenning** [comment]
The import map is modified by each microfrontend during it's CI deployment. See https://github.com/react-microfrontends/planets/blob/41ba0aaf9005b5300cc28ad5f4eac024eae06e2b/.circleci/config.yml#L69-L73 for where that's done. Also see related https://github.com/single-spa/import-map-deployer and https://single-spa.js.org/docs/recommended-setup#deployment-and-continuous-integration-ci
