### ISSUE TITLE
Where is the source code?

### ISSUE THREAD

**Issue by treblam** [react-microfrontends/shared-dependencies#4]
There is no src directory?

**Comment by HomiG** [comment]
That's intended, you could statically serve this folder to get the importmaps.json

**Comment by HomiG** [comment]
> There is no src directory?

That's intended, you could statically serve this folder to get the importmaps.json

**Comment by joeldenning** [comment]
The importmap.json is the source file. The CI config updates a live import map whenever a change to importmap.json file is merged
